# Generated by Django 4.1.5 on 2023-01-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("films_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="slug",
        ),
    ]
