# Generated by Django 4.1.5 on 2023-01-16 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("films_app", "0002_alter_film_release_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={
                "ordering": ["first_name"],
                "verbose_name": "Актеры",
                "verbose_name_plural": "Актеры",
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={
                "ordering": ["genre"],
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.AlterModelOptions(
            name="similarfilm",
            options={
                "ordering": ["film"],
                "verbose_name": "Похожий фильм",
                "verbose_name_plural": "Похожие фильмы",
            },
        ),
        migrations.RemoveField(
            model_name="film",
            name="genre",
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="films",
                to="films_app.genre",
                verbose_name="Жанр",
            ),
        ),
    ]
